language: node_js
node_js:
  - "7"
branches:
  only:
  - master
cache:
  yarn: true
  directories:
    - node_modules
    - .cache
    - public
deploy:
  provider: script
  script: 'pwd && ls && yarn deploy:ci'
  skip_cleanup: true
  on:
    branch: master
