language: node_js
node_js:
  - "7"
branches:
  only:
  - master
cache:
  yarn: true
  directories:
    - node_modules
    - .cache
    - public
deploy:
  provider: script
  script:
    - 'yarn deploy:ci'
    - 'pwd'
    - 'ls'
  skip_cleanup: true
  on:
    branch: master
