title: Holidays
baseURL: "https://holidaze.florenceltf.com/"
languageCode: "en-au"
taxonomies:
  country: countries
params:
  status: Currently In Isolation
markup:
  goldmark:
    renderer:
      unsafe: true
