version: 2
jobs:

  build:
    branches:
      ignore:
        - gh-pages

    docker:
      - image: circleci/node:carbon

    resource_class: xlarge

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}

      - checkout

      - run:
          name: Install deps
          command: npm install

      - deploy:
          name: Deploy to github pages
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME
              npm run deploy
            else
              npm run build
            fi

      - save_cache:
          # Update the cache to have the latest contents
          key: source-v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ".git"
            - node_modules
            - public
            - .cache
