name: Hugo Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.72.0'

      - name: Build
        run: hugo

      - name: Deploy
        run: echo "Deploy!"
